"""Aplicar convención de nombres

Revision ID: f3e52bf7850e
Revises: cec58513e780
Create Date: 2024-12-22 03:15:18.583727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e52bf7850e'
down_revision: Union[str, None] = 'cec58513e780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_blogs_author_id_users'), 'users', ['author_id'], ['pk'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_blogs_author_id_users'), type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
