name: Deploy Application

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Normalize tag and set latest
        id: vars
        run: |
          echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "LATEST_TAG=latest" >> $GITHUB_ENV
          echo "REPO=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Pull and tag Docker image
        run: |
          docker pull ghcr.io/${{ env.REPO }}/api-blog:${{ env.TAG }}
          docker tag ghcr.io/${{ env.REPO }}/api-blog:${{ env.TAG }} ghcr.io/${{ env.REPO }}/api-blog:latest

      - name: Push both tags
        run: |
          docker push ghcr.io/${{ env.REPO }}/api-blog:${{ env.TAG }}
          docker push ghcr.io/${{ env.REPO }}/api-blog:latest

      - name: Deploy with Docker Compose
        run: |
          cd /home/rp-juana/api-blog
          docker compose down
          docker compose up -d