name: Lint with Ruff

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    name: "Lint (Python ${{ matrix.python-version }})"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format

      # si no hay errores, se puede hacer un commit
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: success()
        with:
          commit_message: "Apply Ruff fixes"
          commit_user_name: "Ruff Bot"
          commit_author: Author ${{ github.actor }}